  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/en/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/en/post/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/en/portfolio/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/en/about/"

  [[main]]
  name = "Contact"
  weight = 500
  identifier = "contact"
  url = "/en/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/en/imprint/"
