
title = "Carey's Blog"
author = "Carey Chang"
#copyright = "2020-2021"
description = "Hi, I'm Carey."
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Fonts
googleFonts = ["Noto+Sans", "Noto+Sans:ital,wght@0,400;0,700;1,700"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.

[[socialIcons]]
icon = "fab fa-facebook"
title = "Facebook"
url = "https://www.facebook.com/JKLinTW/"

[[socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/JKLinTW"

[[socialIcons]]
icon = "fab fa-instagram"
title = "Instagram"
url = "https://www.instagram.com/JKLinTW"

[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/JKLinTW/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/JKL-TW"

[[socialIcons]]
icon = "fas fa-envelope"
title = "E-mail"
url = "mailto:jkl0114@gmail.com"
